sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/traviscli
    - secure: "FwHY+m+l8I+ybkZ3IBq6kfBQX4q7qgCG7knh3iFAB77i4XeAXQ1r0brD7ikYNVTbyclFRVVszu9mPnx0ec/0MZNc7XEu//PIN+vwGeIX5bgNo0jykLVC5f7+K8eMb5DliIpbKUo4D97K1zT//KXsX7MVWItuyDWtSOiknYQBbNqGUxaEIO4icyWenv+ABKhCP+GiYdmiLN1vP9UHVSF0GZQzG9mIcY4nqW1tIoA/Irje8ebof098i8tCOgT6iJsb+DljBiE1KJjAn/gXVTw1buWuKvpTOc8sD7liNVdcq2gqVgEP0aPeCMyTLK8Ixgvy+1nT2+jd7E5MxK9U5zWgWqeYWa+EvRk0CHff/gZudQAGZ/1Se37lCnKQJHPMPL3/V1BIh0d1xsl7MsVTHhXXiZzUiJ4WysF1bx9Py4I7Bth0ySCeZgPsY3g4fppiiO0Hgx6+/WsB/Helg6PRL9SmbT4I2wNCvq4gB/XxZ9NGhnDi4Iyh1uJBEiagWPlDU1OD+G/ihUjRkaYTHWHr/Pa0b1cJV2fWyLFSENbdRAV8l6JjrdWItSXdMhNK/XFdSrpBl7I2XWv0Z1RGQrI8nPXzO0YRfCCm8bZrXk/cqPAm6g9xj8rdNd3PxUHL/HSttgwzRpdNvUNKGhfcJPk3LFHSa9RKtXO61pUpgPeQnmd5xuE="